// <auto-generated />
using System;
using FitafeAPI.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitafeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.MenuEntites.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calaroies");

                    b.Property<string>("Description");

                    b.Property<string>("ImagePath");

                    b.Property<int>("MealId");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("MealId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.MenuEntites.Meal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("MenuSectionId");

                    b.Property<string>("Name");

                    b.Property<int?>("OrderItemID");

                    b.Property<double>("Price");

                    b.Property<int>("TotalCalories");

                    b.HasKey("ID");

                    b.HasIndex("MenuSectionId");

                    b.HasIndex("OrderItemID");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.MenuEntites.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.MenuEntites.MenuSection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.ToTable("MenuSections");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.OrderEntities.DeliveryAdress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress");

                    b.Property<string>("City");

                    b.Property<int>("OrderId");

                    b.Property<string>("PhoneNumer");

                    b.HasKey("ID");

                    b.HasIndex("OrderId");

                    b.ToTable("DeliveryAdresses");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.OrderEntities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<string>("Note");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.OrderEntities.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderID");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.OrderEntities.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.RateEntities.OrderRate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int>("CustomerId");

                    b.Property<int?>("MealID");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Title");

                    b.Property<int>("Value");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MealID");

                    b.ToTable("OrderRates");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.RateEntities.RestaurantRate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int>("CustomerId");

                    b.Property<int?>("RestaurantID");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Title");

                    b.Property<int>("Value");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantID");

                    b.ToTable("RestaurantRates");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.StatusDetail", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<int>("OrderStatusId");

                    b.Property<string>("Comment");

                    b.Property<int?>("EmployeeID");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("OrderId", "OrderStatusId");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("StatusDetails");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.UsersEntities.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress");

                    b.Property<string>("City");

                    b.Property<string>("ContactPhone");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("EmailAdress");

                    b.Property<string>("FullName");

                    b.Property<string>("ImagePath");

                    b.Property<int>("NumberOfOrders");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.UsersEntities.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Adress");

                    b.Property<string>("City");

                    b.Property<string>("ContactPhone");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("EmailAdress");

                    b.Property<string>("FullName");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Password");

                    b.Property<int?>("RestaurantID");

                    b.Property<int>("RoleId");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.UsersEntities.Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress");

                    b.Property<string>("City");

                    b.Property<string>("ContactPhone");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("EmailAdress");

                    b.Property<string>("FullName");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.UsersEntities.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cheef");

                    b.Property<bool>("Delivery");

                    b.Property<bool>("Owner");

                    b.Property<bool>("Witer");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.RestaurantEntities.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("ContactPhone");

                    b.Property<int>("DeliveryCharge");

                    b.Property<int>("DeliveryRange");

                    b.Property<string>("Description");

                    b.Property<string>("EmailAdress");

                    b.Property<string>("Experince");

                    b.Property<string>("ImagePath");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsOpen");

                    b.Property<int?>("MenuID");

                    b.Property<string>("Name");

                    b.Property<int?>("OwnerID");

                    b.Property<string>("Story");

                    b.Property<string>("WhatWeDo");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.MenuEntites.Item", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.MenuEntites.Meal", "Meal")
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.MenuEntites.Meal", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.MenuEntites.MenuSection", "MenuSection")
                        .WithMany("Meals")
                        .HasForeignKey("MenuSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FitafeAPI.Business.Persistence.Entities.OrderEntities.OrderItem")
                        .WithMany("Meals")
                        .HasForeignKey("OrderItemID");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.MenuEntites.MenuSection", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.MenuEntites.Menu")
                        .WithMany("MenuSections")
                        .HasForeignKey("MenuID");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.OrderEntities.DeliveryAdress", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.OrderEntities.Order", "Order")
                        .WithMany("DeliveryAdresses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.OrderEntities.Order", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.UsersEntities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.OrderEntities.OrderItem", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.OrderEntities.Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.RateEntities.OrderRate", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.UsersEntities.Customer", "Customer")
                        .WithMany("OrderRates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FitafeAPI.Business.Persistence.Entities.MenuEntites.Meal")
                        .WithMany("Rates")
                        .HasForeignKey("MealID");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.RateEntities.RestaurantRate", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.UsersEntities.Customer", "Customer")
                        .WithMany("RestaurntRates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FitafeAPI.Business.Persistence.RestaurantEntities.Restaurant")
                        .WithMany("Rates")
                        .HasForeignKey("RestaurantID");
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.StatusDetail", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.UsersEntities.Employee")
                        .WithMany("StatusDetails")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("FitafeAPI.Business.Persistence.Entities.OrderEntities.Order", "Order")
                        .WithMany("Statuses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FitafeAPI.Business.Persistence.Entities.OrderEntities.Status", "Status")
                        .WithMany("Statuses")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.Entities.UsersEntities.Employee", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.RestaurantEntities.Restaurant")
                        .WithMany("Employees")
                        .HasForeignKey("RestaurantID");

                    b.HasOne("FitafeAPI.Business.Persistence.Entities.UsersEntities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FitafeAPI.Business.Persistence.RestaurantEntities.Restaurant", b =>
                {
                    b.HasOne("FitafeAPI.Business.Persistence.Entities.MenuEntites.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID");

                    b.HasOne("FitafeAPI.Business.Persistence.Entities.UsersEntities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID");
                });
#pragma warning restore 612, 618
        }
    }
}
